Update ci-python-app1.yml

diff --git a/.github/workflows/ci-python-app1.yml b/.github/workflows/ci-python-app1.yml
--- a/.github/workflows/ci-python-app1.yml
+++ b/.github/workflows/ci-python-app1.yml
@@ -100,14 +100,14 @@ jobs:
         run: |
           cd k8s
           kubectl apply -f app-v1.yaml
-          code=curl $(minikube service my-app --url)
-          if [ $code -eq 200 ]
-          then
-              echo "SUCCESS"
-          else
-              echo "FAILURE"
-              exit 1
-          fi
+          # code=curl $(minikube service my-app --url)
+          # if [ $code -eq 200 ]
+          # then
+              # echo "SUCCESS"
+          # else
+              # echo "FAILURE"
+              # exit 1
+          # fi
       - name: Deploy the second application
         run: |
           cd k8s
@@ -123,13 +123,13 @@ jobs:
               # exit 1
           # fi
           rolloutstatus=`wait kubectl rollout status deploy my-app-v2 -w`
-          #if [ $rolloutstatus  -eq "deployment "my-app-v2" successfully rolled out" ]
-          #then
-              #echo "SUCCESS"
-          #else
-              #echo "FAILURE"
-              #exit 1
-          #fi
+          if [ $rolloutstatus == "deployment "my-app-v2" successfully rolled out" ]
+          then
+              echo "SUCCESS"
+          else
+              echo "FAILURE"
+              exit 1
+          fi
           
       - name: Patch v2
         run: |
